#!/bin/sh
##########################################################################
# Application restart script
#
# Author: David Medders
# Editor: Maxwell Kapral (I suspect this script is no longer relevant)
##########################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: restarting httpd"
stopservice httpd
sleep 1
startservice httpd

exit 0

##########################################################################
# Note: httpd intermittently goes to 100% CPU, cycling the daemon clears
#       the condition.
##########################################################################
