#!/bin/sh
##########################################################################
# Application restart script
#
# Author: David Medders
# Editor: Maxwell Kapral
##########################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: restarting httpd"
killall httpd
sleep 1
httpd -S -m 443

exit 0

##########################################################################
# Note: httpd intermittently goes to 100% CPU, cycling the daemon clears
#       the condition.
##########################################################################
