#!/bin/sh
##########################################################################
# clock update script - run by cron
#
# Author: David Medders
##########################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: started"

NTPIP=`nvram get ntp_server`

ntpclient $NTPIP

if [ $? -ne 0 ]; then   # update failed
  wanlogger $LOG_WARNING "$BN: ntpclient failed for $NTPIP #10 $BN"
  exit 1
fi

wanlogger $LOG_DEBUG "$BN: complete"

exit 0
