#!/bin/sh
##########################################################################
# clock update script - run by cron
#
# Author: David Medders
# Editor: Maxwell Kapral
##########################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: started"

NTPSERVER="`nvram get ntp_server`"

ntpclient $NTPSERVER

if [ $? -ne 0 ]; then   # update failed
  wanlogger $LOG_WARNING "$BN: ntpclient failed for $NTPSERVER #10 $BN"
  exit 1
fi

wanlogger $LOG_DEBUG "$BN: complete"

exit 0
