#!/bin/sh
#########################################################################
#
# configure WAN routes
#
# parameters:
#   default: standard WAN and WAN2 routing
#   wan1: all traffic to WAN
#   wan2: all traffic to WAN2
#
# Author: David Medders
# Editor: Maxwell Kapral
#########################################################################

. /jffs/scripts/wan/global

#LOGLEVEL=$LOG_DEBUG   # overriding LOGLEVEL
#FILELEVEL=$LOGLEVEL

if [ $# -ne 1 ]; then
  echo "Usage: $BN <default|wan1|wan2|down>"
  wanlogger $LOG_ERR "Usage: $BN <default|wan1|wan2|down>"
  exit 1
fi

tableroutes() {
  ip route delete default

  TABLEROUTE=`ip route show table 100 | grep default`
  if [ -n "$TABLEROUTE" ]; then
    ROUTEIP=`echo $TABLEROUTE | cut -d ' ' -f3`
    ROUTEIF=`echo $TABLEROUTE | cut -d ' ' -f5`
    ip route delete via $ROUTEIP dev $ROUTEIF table 100
  fi

  TABLEROUTE=`ip route show table 200 | grep default`
  if [ -n "$TABLEROUTE" ]; then
    ROUTEIP=`echo $TABLEROUTE | cut -d ' ' -f3`
    ROUTEIF=`echo $TABLEROUTE | cut -d ' ' -f5`
    ip route delete via $ROUTEIP dev $ROUTEIF table 200
  fi
}

case $1 in
  "default" )
    wanlogger $LOG_NOTICE "$BN: configuring $1 routing #07 $1 "

    tableroutes

    ip route add default via $(nvram get wan1_gateway) dev $(nvram get wan1_ifname)

    ip rule add from $NET2 table 100
    ip rule add from $NET3 table 100
    ip rule add from $NET4 table 100
    ip route add default via $(nvram get wan1_gateway) \
      dev $(nvram get wan1_ifname) table 100

    ip rule add from $NET1 table 200
    ip route add default via $(nvram get wan2_gateway) \
      dev $(nvram get wan2_ifname) table 200

    RETVAL=0
    ;;
  "wan1" )
    wanlogger $LOG_NOTICE "$BN: routing all traffic to $1 #07 $1 "

    tableroutes

    ip rule del from $NET3 table 100
    ip rule del from $NET4 table 100
    ip rule del from $NET2 table 100
    ip rule del from $NET1 table 200

    ip route add default via $(nvram get wan1_gateway) dev $(nvram get wan1_ifname)
    ip route add default via $(nvram get wan1_gateway) \
      dev $(nvram get wan1_ifname) table 100
    ip route add default via $(nvram get wan1_gateway) \
      dev $(nvram get wan1_ifname) table 200

    RETVAL=0
    ;;
  "wan2" )
    wanlogger $LOG_NOTICE "$BN: routing all traffic to $1 #07 $1 "

    tableroutes

    ip rule del from $NET3 table 100
    ip rule del from $NET4 table 100
    ip rule del from $NET2 table 100
    ip rule del from $NET1 table 200

    ip route add default via $(nvram get wan2_gateway) dev $(nvram get wan2_ifname)
    ip route add default via $(nvram get wan2_gateway) \
      dev $(nvram get wan2_ifname) table 100
    ip route add default via $(nvram get wan2_gateway) \
      dev $(nvram get wan2_ifname) table 200

    RETVAL=0
    ;;
  "down" )
    wanlogger $LOG_WARNING "$BN: no wan up, deleting routes"

    tableroutes

    ip rule del from $NET3 table 100
    ip rule del from $NET4 table 100
    ip rule del from $NET2 table 100
    ip rule del from $NET1 table 200

    RETVAL=0
    ;;
  * )
    echo "$BN: Unrecognized selection: $1"
    wanlogger $LOG_ERR "$BN: Unrecognized selection: $1"
    RETVAL=1
    ;;
esac

if [ $RETVAL -eq 0 ]; then

  # add route(s) for Grande router segment
  ip route del $MODEM1_CIDR dev $MODEM1_IFNAME
  ip route add $MODEM1_CIDR dev $MODEM1_IFNAME

  ip route flush cache

  echo "$1 `date '+%d%b%g %H%M%S'`" > $ROUTESTATFILE

  wanlogger $LOG_NOTICE "$BN: route set to $1"

  $DNSUPDATE
fi

exit $RETVAL

