#!/bin/sh
############################################################################
# linkup forces up a link that is in recovering state
#
# Author: David Medders
############################################################################

. /jffs/scripts/wan/global

if [ $# -ne 1 ]; then
  echo "Usage: $BN <WAN name>"
  exit 1
fi

STATFILE=$TMPDIR/$STATROOT.$1

if [ -f "$STATFILE" ]; then   # check that status file exists
  WANSTAT=`cat $STATFILE | cut -f1 -d' '`

  if [ "$WANSTAT" = "recovering" ]; then
    PLIST=`ps | grep -E "\{linkd\}.*linkd ${1}" | awk '{print $1}'`
    if [ -n "$PLIST" ]; then
      for PID in $PLIST; do
        kill -SIGUSR1 $PID >/dev/null 2>&1
      done
      rm $STATFILE
      RETVAL=0
    else
      echo "$BN: linkd process not found"
      RETVAL=1
    fi
  else
    echo "$BN: $1 in $WANSTAT status, state not changed"
    RETVAL=2
  fi
else
  echo "$BN: Status file not found for $1"
  RETVAL=3
fi

exit $RETVAL

