#!/bin/sh
##############################################################################
# wanlogger file management scripts - should run daily at 0000
# 
# Rotates log files daily, summarizes contents, and reports to email_admin
#
# Summary includes: link failures, route failures, WAN failures, route changes,
#   memory use, and top processes
##############################################################################

. /jffs/scripts/wan/global

MV=/bin/mv
FSUFFIX=$(expr `date +%j` % $LOGDAYS)
OFILE=$TMPDIR/logwatch.$FSUFFIX
TFILE=$TMPDIR/lw.$$
SRCFILE=$LOGFILE.$FSUFFIX
SERVER=$(nvram get email_server)
USER=$(nvram get email_user)
PASSWORD=$(nvram get email_passwd)
DEST=$(nvram get email_admin)
HOST=$(nvram get router_name).$(nvram get wan_get_domain)
FROM=root@$HOST
NAME=root

$MV $LOGFILE $SRCFILE

touch $LOGFILE

date >$OFILE; echo >>$OFILE

echo "Source file: $SRCFILE" >>$OFILE; echo >>$OFILE

uptime >>$OFILE; echo >>$OFILE

top -b -n1 | head -n 10 >> $OFILE; echo >>$OFILE

ls -1 $TMPDIR/$STATROOT* | while read LINE; do
  NAME=`basename $LINE`
  echo -n "$NAME: " >>$OFILE
  cat $LINE >>$OFILE
done

# ping failures
echo >>$OFILE
echo "Ping failures (total and max sequential)" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=0
  MAXFAIL=0
  grep "#01 $WAN " $SRCFILE | cut -f2 -d '#' >$TFILE
  while read LINE; do
    CNT=`echo $LINE | cut -f3 -d' '`
    FAIL=`echo $LINE | cut -f4 -d' '`
    FAILTOTAL=$(($FAILTOTAL+$CNT))
    if [ $FAIL -gt $MAXFAIL ]; then
      MAXFAIL=$FAIL
    fi
  done < $TFILE
  
  echo "  $WAN: $FAILTOTAL $MAXFAIL" >>$OFILE
done

# route failures
echo >>$OFILE
echo "Route failures (total and max sequential)" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=0
  MAXFAIL=0
  grep "#02 $WAN " $SRCFILE | cut -f2 -d '#' >$TFILE
  while read LINE; do
    CNT=`echo $LINE | cut -f3 -d' '`
    FAIL=`echo $LINE | cut -f4 -d' '`
    FAILTOTAL=$(($FAILTOTAL+$CNT))
    if [ $FAIL -gt $MAXFAIL ]; then
      MAXFAIL=$FAIL
    fi
  done <$TFILE
  
  echo "  $WAN: $FAILTOTAL $MAXFAIL" >>$OFILE
done

# wan down events
echo >>$OFILE
echo "wan down events" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=`grep "#03 $WAN " $SRCFILE | cut -f2 -d '#' | wc -l`
  echo "  $WAN: $FAILTOTAL" >>$OFILE
done

# wan link events
echo >>$OFILE
echo "wan link events" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=`grep "#04 $WAN " $SRCFILE | cut -f2 -d '#' | wc -l`
  echo "  $WAN: $FAILTOTAL" >>$OFILE
done

# wan recovering events
echo >>$OFILE
echo "wan recovering events" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=`grep "#05 $WAN " $SRCFILE | cut -f2 -d '#' | wc -l`
  echo "  $WAN: $FAILTOTAL" >>$OFILE
done

# wan up events
echo >>$OFILE
echo "wan up events" >>$OFILE

for WAN in $WANLIST; do
  FAILTOTAL=`grep "#06 $WAN " $SRCFILE | cut -f2 -d '#' | wc -l`
  echo "  $WAN: $FAILTOTAL" >>$OFILE
done

# route configuration events
echo >>$OFILE
echo "Route configuration events" >>$OFILE

grep "#07" $SRCFILE | cut -f2 -d '#' |sort >$TFILE

if [ `wc -l <$TFILE` -eq 0 ]; then
  echo "  none" >>$OFILE
else
  CFG=""
  CNT=0
  while read LINE; do
    CFGNAME=`echo $LINE | cut -f2 -d' '`
    if [ "$CFGNAME" = "$CFG" ]; then 
      CNT=$(($CNT+1))
    else
      if [ $CNT -gt 0 ]; then
        echo "  $CFG: $CNT" >>$OFILE
      fi
      CFG=$CFGNAME
      CNT=1
    fi
  done < $TFILE
  
  echo "  $CFG: $CNT" >>$OFILE
fi

# process restarts
echo >>$OFILE
echo "Process restarts" >>$OFILE

grep "#08" $SRCFILE | cut -f2 -d '#' |sort >$TFILE

if [ `wc -l <$TFILE` -eq 0 ]; then
  echo "  none" >>$OFILE
else
  PROC=""
  CNT=0
  while read LINE; do
    PNAME=`echo $LINE | cut -f2 -d' '`
    if [ "$PNAME" = "$PROC" ]; then 
      CNT=$(($CNT+1))
    else
      if [ $CNT -gt 0 ]; then
        echo "  $PROC: $CNT" >>$OFILE
      fi
      PROC=$PNAME
      CNT=1
    fi
  done < $TFILE
  
  echo "  $PROC: $CNT" >>$OFILE
fi

# configuration reloads
echo >>$OFILE
echo "Configuration reloads" >>$OFILE

grep "#09" $SRCFILE | cut -f2 -d '#' |sort >$TFILE

if [ `wc -l <$TFILE` -eq 0 ]; then
  echo "  none" >>$OFILE
else
  PROC=""
  CNT=0
  while read LINE; do
    PNAME=`echo $LINE | cut -f2 -d' '`
    if [ "$PNAME" = "$PROC" ]; then 
      CNT=$(($CNT+1))
    else
      if [ $CNT -gt 0 ]; then
        echo "  $PROC: $CNT" >>$OFILE
      fi
      PROC=$PNAME
      CNT=1
    fi
  done < $TFILE
  
  echo "  $PROC: $CNT" >>$OFILE
fi

# process failures
echo >>$OFILE
FAILTOTAL=`grep "#10 " $SRCFILE | cut -f2 -d '#' | wc -l`
echo "Process failures: $FAILTOTAL" >>$OFILE

rm $TFILE

MSG=`cat $OFILE`

$SENDSTATUS logwatch "$MSG"

