#!/bin/sh
##############################################################################
# Initiate monitord re-read of global configuration
#
# Author: David Medders
##############################################################################

. /jffs/scripts/wan/global

#LOGLEVEL=$LOG_DEBUG    # overriding LOGLEVEL
#FILELEVEL=$LOGLEVEL

PIDFILE=$PIDDIR/monitord.pid
if [ -f $PIDFILE ]; then
  wanlogger $LOG_DEBUG "$BN: sending SIGUSR2 to monitord"
  echo "$BN: sending SIGUSR2 to monitord"
  kill -SIGUSR2 $(cat $PIDFILE)
else
  wanlogger $LOG_DEBUG "$BN: no PID file for monitord"
  echo "$BN: no PID file for monitord"
fi

##############################################################################
