#!/bin/sh
##############################################################################
# Initiate monitord re-read of global configuration
#
# Author: David Medders
##############################################################################

. /jffs/scripts/wan/global

#LOGLEVEL=$LOG_DEBUG    # overriding LOGLEVEL
#FILELEVEL=$LOGLEVEL

PLIST=`ps | grep -E "\{monitord\}" | awk '{print $1}'`
if [ -n "$PLIST" ]; then
  wanlogger $LOG_DEBUG "$BN: sending SIGUSR2 to monitord"
  echo "$BN: sending SIGUSR2 to monitord"
  for PID in $PLIST; do
    kill -SIGUSR2 $PID >/dev/null 2>&1
  done
else
  wanlogger $LOG_DEBUG "$BN: no PID for monitord"
  echo "$BN: no PID for monitord"
fi

##############################################################################
