#!/bin/sh
###############################################################################
# route script for startup configuration
#
# Author: David Medders
# Editor: Maxwell Kapral
# Based on the work of John Barbieri
###############################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: start"

wanlogger $LOG_DEBUG "$BN: flushing rules"

ip rule flush

wanlogger $LOG_DEBUG "$BN: building rules and tables"

ip rule add lookup main prio 32766
ip rule add lookup default prio 32767

ip rule add from $(nvram get wan1_ipaddr) table 100 prio 100
ip rule add fwmark 0x100 table 100 prio 101

ip rule add from $(nvram get wan2_ipaddr) table 200 prio 200
ip rule add fwmark 0x200 table 200 prio 201

# subnet for trading traffic
# NET1=`nvram get lan_ipaddr|cut -f1-3 -d'.'`.192/26
# ip rule add from $NET1 prio 202

ip route flush table 100
ip route flush table 200

for TABLE in 100 200; do
  ip route | grep link | while read ROUTE; do
    wanlogger $LOG_DEBUG "$BN: TABLE $TABLE to ROUTE $ROUTE"
    ip route add table $TABLE to $ROUTE
  done
done

ip route add table 100 default via $(nvram get wan1_gateway)
ip route add table 200 default via $(nvram get wan2_gateway)

wanlogger $LOG_DEBUG "$BN: Deleting default route"
ip route delete default

if [ -f "/opt/sbin/ip" ]; then
    # route to balance traffic across wan1 & wan2
    /opt/sbin/ip route add default scope global \
      nexthop via $(nvram get wan1_gateway) dev $(nvram get wan1_ifname) weight $WEIGHTwan1 \
      nexthop via $(nvram get wan2_gateway) dev $(nvram get wan2_ifname) weight $WEIGHTwan2
    wanlogger $LOG_INFO "$BN: Load Balancing Target"
else
    # default route for main subnet traffic
    route add default gw $(nvram get wan1_gateway)
fi

# add routes for route status checks

for WAN in $WANLIST; do
  route add -host `nvram get route_ip` gw `nvram get ${WAN}_gateway` \
    `nvram get ${WAN}_ifname`
  route add -host `nvram get route_ip2` gw `nvram get ${WAN}_gateway` \
    `nvram get ${WAN}_ifname`
done

ip route flush cache

echo "default `date '+%d%b%g %H%M%S'` route" > $ROUTESTATFILE  # write status

$CHANGEWAN

wanlogger $LOG_DEBUG "$BN: exit"

exit 0

