#!/bin/sh
###############################################################################
# route script for startup configuration
#
# Author: David Medders
# Editor: Maxwell Kapral
# Based on the work of John Barbieri
###############################################################################

. /jffs/scripts/wan/global

wanlogger $LOG_DEBUG "$BN: start"

wanlogger $LOG_DEBUG "$BN: flushing rules"

ip rule flush

wanlogger $LOG_DEBUG "$BN: building rules and tables"

ip rule add lookup main prio 32766
ip rule add lookup default prio 32767

ip rule add from $(nvram get wan1_ipaddr) table 100 prio 100
ip rule add fwmark 0x100 table 100 prio 101

ip rule add from $(nvram get wan2_ipaddr) table 200 prio 200
ip rule add fwmark 0x200 table 200 prio 201

ip route flush table 100
ip route flush table 200

for TABLE in 100 200; do
  ip route | grep link | while read ROUTE; do
    wanlogger $LOG_DEBUG "$BN: TABLE $TABLE to ROUTE $ROUTE"
    ip route add table $TABLE to $ROUTE
  done
done

ip route add default via $(nvram get wan1_gateway) table 100
ip route add default via $(nvram get wan2_gateway) table 200

wanlogger $LOG_DEBUG "$BN: Deleting default route"
ip route delete default

ip route add default via $(nvram get wan1_gateway) dev $(nvram get wan1_ifname)

# add route(s) for Grande router segment
ip route del $MODEM1_CIDR dev $MODEM1_IFNAME
ip route add $MODEM1_CIDR dev $MODEM1_IFNAME

ip route flush cache

echo "default `date '+%d%b%g %H%M%S'` route" > $ROUTESTATFILE  # write status

$CHANGEWAN

wanlogger $LOG_DEBUG "$BN: exit"

exit 0

