name: Pre-Releases

on:
  push:
    branches: '*-dev'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          try {
            const { data } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "dev"
            });
            github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: data.id
            });
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/dev"
            });
          } catch (e) {
            console.log(e);
          }
    - uses: actions/checkout@v4
    - id: package
      run: |
        echo branch=$(git branch --show-current) >> $GITHUB_ENV
        tar cvf onchange.tar --{owner,group}=root --directory=jffs/etc/config .
        tar cvf scripts.tar --{owner,group}=root --directory=jffs/scripts/wan .
        tar cvf bin.tar --{owner,group}=root --directory=jffs/bin .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "onchange.tar,scripts.tar,bin.tar"
        prerelease: true
        commit: ${{ env.branch }}
        tag: "dev"
        makeLatest: true
