name: Releases

on: 
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run : |
        cd ~/jffs/etc/config
        tar cvf onchange.tar *
        cd ~/jffs/scripts/wan
        tar cvf scripts.tar *
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "~/jffs/etc/config/onchange.tar,~/jffs/scripts/wan/scripts.tar"
        prerelease: true
        tag: "latest"
