name: Releases

on: 
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run : |
        tar cvf onchange.tar jffs/etc/config/*
        tar cvf scripts.tar jffs/scripts/wan/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "onchange.tar,scripts.tar"
        prerelease: true
        tag: "latest"
