name: Releases

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const { data } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          })
          github.rest.repos.deleteRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: data.id
          })
          github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "tags/latest"
          })
    - uses: actions/checkout@v2
    - run: |
        tar cvf onchange.tar --directory=jffs/etc/config .
        tar cvf scripts.tar --directory=jffs/scripts/wan .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "onchange.tar,scripts.tar"
        prerelease: false
        tag: "latest"
        allowUpdates: true
        makeLatest: true
        name: "latest"
