name: Releases

on: 
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "jffs/etc/config/*,jffs/scripts/wan/*"
        prerelease: true
        tag: "latest"
