name: Releases

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v6
      id: get-latest
      with:
        script: |
          const { data } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          })
          return data.id
        result-encoding: string
    - run: echo "${{steps.get-latest.outputs.result}}"