name: Releases

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: |
        tar cvf onchange.tar --directory=jffs/etc/config .
        tar cvf scripts.tar --directory=jffs/scripts/wan .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "onchange.tar,scripts.tar"
        prerelease: false
        commit: main
        tag: ${{ github.event.repository.updated_at }}
        allowUpdates: true
        makeLatest: true
