name: Releases

on:
  push:
    branches: main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const releaseId = github.rest.releases.tags.get({
            owner: context.repo.owner
            repo: context.repo.repo
            tag: "latest"
          })
          github.rest.releases.delete({
            owner: context.repo.owner
            repo: context.repo.repo
            release_id: releaseId.id
          })
          github.rest.git.refs.delete({
            owner: context.repo.owner
            repo: context.repo.repo
            ref: "latest"
          })
    - uses: actions/checkout@v2
    - run: |
        tar cvf onchange.tar --directory=jffs/etc/config .
        tar cvf scripts.tar --directory=jffs/scripts/wan .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "onchange.tar,scripts.tar"
        prerelease: false
        tag: "latest"
        allowUpdates: true
        makeLatest: true
        name: "latest"
